### ISSUE TITLE
CreateFtsIndex doesn't use orderingColumnNames

### ISSUE THREAD

**Issue by edwin-jsi** [thebracket/LanceDbCSharp#13]

**Comment by thebracket** [comment]
This isn't implemented in LanceDb itself. See `lancedb/python/lancedb/table.py`. It states:

```
ordering_field_names:
            A list of unsigned type fields to index to optionally order
            results on at search time.
            only available with use_tantivy=True
```

And later on gives you the choice of "legacy" Tantivy (implemented on the Python side) or using LanceDb.
